In [54]:
import numpy as np

In [55]:
x=np.genfromtxt(r"C:\Users\sujit\Downloads\tipsf.csv",delimiter=",",skip_header=1)

In [56]:
x

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

In [57]:
#1>what is the total bill value

np.sum(x[:,1])

4827.77

In [58]:
#2>what is the total tip value

np.sum(x[:,2])

731.5799999999999

In [59]:
#3>count of how many times sun,sat,thu,fri are there.
z=np.unique(x[:,5],return_counts=True)
a,b=z
j=0
for i in a:
    if(i==0):
        print("sunday = ",b[j])
        j+=1
    elif(i==1):
        print("saturday = ",b[j])
        j+=1
    elif(i==2):
        print("thursday = ",b[j])
        j+=1
    elif(i==3):
        print("friday = ",b[j])
        j+=1   

sunday =  87
saturday =  76
thursday =  62
friday =  19


In [60]:
#4>how many smokers are there
q=np.sum(x[:,4])
print(int(q),"smokers are there")

93 smokers are there


In [61]:
#5>what is the average tip given by female and male
a=np.sum(x[:,2].take(np.where(x[:,3]==0)))
b=np.sum(x[:,2].take(np.where(x[:,3]==1)))
z=np.unique(x[:,3],return_counts=True)
q,w=z
print(a/w[0],"average tip given by female")
print(b/w[1],"average tip given by male")

2.8334482758620685 average tip given by female
3.0896178343949043 average tip given by male


In [62]:
#6>how much amount have been spent by female and male.
a=np.sum(x[:,1].take(np.where(x[:,3]==0)))
b=np.sum(x[:,1].take(np.where(x[:,3]==1)))
print("total amount spent by female: ",np.round(a))
print("total amount spent by male: ",np.round(b))

total amount spent by female:  1571.0
total amount spent by male:  3257.0


In [63]:
#7>what is the min and max tip given 
max_tip=np.max(x[:,2])
min_tip=np.min(x[:,2])
print("maximum tip is ",max_tip)
print("minimum tip is ",min_tip)

maximum tip is  10.0
minimum tip is  1.0


In [64]:
#8>how many male and female are going for dinner and lunch
z=np.unique(x[:,3].take(np.where((x[:,6]==1))),return_counts=True)      #lunch        0 means female 1 means male
a,b=z
y=np.unique(x[:,3].take(np.where((x[:,6]==0))),return_counts=True)       #dinner
c,d=y
for i in a:
    if(i==0):
        print("total female going for lunch",b[0])
        print("total female going for dinner",d[0])
    else:
         print("total male going for lunch",b[1])
         print("total female going for dinner",d[1])

total female going for lunch 35
total female going for dinner 52
total male going for lunch 33
total female going for dinner 124


In [65]:
#9>find out the average size
z=np.unique(x[:,7],return_counts=True)
a,b=z
avg=np.sum(x[:,7])/np.sum(b)
print("average of size = ",np.round(avg))

average of size =  3.0


In [66]:
#10>find how many female smokers and male smokers are there
z=np.unique(x[:,3].take(np.where((x[:,4]==1))),return_counts=True)
a,b=z
for i in a:
    if(i==0):
        print("female smokers are : ",b[0])
    else:
        print("male smokers are : ",b[1])

female smokers are :  33
male smokers are :  60


In [69]:
a=np.genfromtxt(r"C:\Users\sujit\Downloads\train_extended.csv",delimiter=",",skip_header=1)

In [70]:
a

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

In [74]:
#1>what is the maximum and minnimum length?

x=np.max(a[:,0])
print("print maximum length is ",x)
y=np.min(a[:,0])
print("print minimum length is ",y)

print maximum length is  7.58349125
print minimum length is  0.0


In [78]:
#2>find out the difference between max and min length.

def f(x):
    return np.max(x)-np.min(x)
np.apply_along_axis(f,0,a[:,0])

array(7.58349125)

In [88]:
#3>find column wise average.
def f1(x):
    return np.sum(x)/200000
np.apply_along_axis(f1,0,a)
    

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

In [101]:
#4>find out all the age whose height is gereater than 0.4
z=a[:,7].take(np.where(a[:,2]>0.4))
print(z.shape)
print(z)

(1, 55336)
[[11. 14. 13. ... 11. 11. 11.]]


In [115]:
#5>what is the average height and weight of the persons whose age is greater than 10.
height=a[:,2].take(np.where(a[:,7]>10))
count=height.shape
weight=a[:,3].take(np.where(a[:,7]>10))
count1=weight.shape
l1=list(count)
l2=list(count1)
print("average height is ",np.sum(height)/l1[1])
print("average weight is ",np.sum(weight)/l2[1])

average height is  0.4085813793498825
average weight is  31.681361864049048


In [118]:
#6>what is the shell weight
np.round(np.sum(a[:,6]))

1326846.0

In [119]:
#7>how many persons belongs to each and every unique age
np.unique(a[:,7],return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

In [122]:
#8>what is the differemce between shucked weight and viscera weight

z=np.sum(a[:,4])
x=np.sum(a[:,5])
print("the difference between shucked weight and viscera weight is ",np.round(z-x))

the difference between shucked weight and viscera weight is  999238.0


In [129]:
#9>what is the average height of the persons whose age is between 14 and 19.

z=a.take(np.where((a[:,7]>14) & (a[:,7]<19)))
sum=np.sum(z)
count=list(z.shape)
print("the average height of the persons whose age is between 14 and 19 is ",np.round(sum/count[1]))

the average height of the persons whose age is between 14 and 19 is  7.0


In [136]:
#10>what is the average weight if we include all shucked weight ,viscera weight and shell weight with weight.
z=np.sum(a[:,3:7])
count=list(a.shape)
print("the average weight if we include all shucked weight ,viscera weight and shell weight with weight is ",np.round(z/count[0]))

the average weight if we include all shucked weight ,viscera weight and shell weight with weight is  45.0
